update

diff --git a/prntl b/prntl
--- a/prntl
+++ b/prntl
@@ -1,69 +1,122 @@
 #!/usr/bin/env bash
 
-PRINT_LOG=1
-LOG_FILE=logfile
-TIME_FORMAT="%d %b %Y %T %z"
-LOG_FORMAT="%time - %log"
-REMOVE_COLORS=0
+LOG_FILE=prntl.log
+TIME_FORMAT='%d %b %Y %T %z'
+LOG_FORMAT='%time - %log'
 
-_show_help() {
+prntl_print_help() {
 cat << EOF
-prntl — print formatted log to STDOUT and log file.
-Use '--no-print' option to write to log file only.
+Print formatted log to STDOUT and log file.
 
-Usage: prntl [OPTION]... < [FILE]
+Usage:
+    prntl [OPTIONS]... [ARGUMENTS]...
+
 Options:
-    -o, --output        set log file. 'logfile' by default
+    -o, --output        set log file name. Default: printl.log.
     -f, --log-format    set log format. Formatting options:
-                            %time   time; see --time-format
-                            %log    log's string
-                            Example: prntl -f 'mylog %time : %log'
+                            %time   time; see '--time-format'.
+                            %log    log string.
+                        Example: prntl -f 'mylog %time : %log'
     -t, --time-format   set time format; see 'date --help'
                         or 'man date' for details.
                         Example: prntl -t '%D %T'
-    -c, --no-color      remove ANSI color codes from log string
-    -p, --no-print      don't print log to STDOUT
+    -c, --no-color      remove ANSI color codes from log string.
+    -p, --no-print      don't print log to STDOUT.
     -h, --help          show this help message and exit.
 EOF
 exit 0
 }
 
-_unknown_option() {
-    echo -e "prntl: $1: Unknown option\nSee 'prntl --help'." && exit 1
-}
-
-_log_formatter() {
+prntl_log_formatter() {
     echo "$1" | sed -e "s/%time/$(date +"$TIME_FORMAT")/g; s/%log/$2/g"
 }
 
-_print_log() {
-    LOG_MESSAGE="$(cat <&0)"
+prntl_print_log() {
+    if [ "$LOG" ]
+    then
+         LOG_MESSAGE="$LOG"
+    else
+        LOG_MESSAGE="$(cat <&0)"
+    fi
 
     ESCAPED_LOG_MESSAGE="$(printf '%s\n' "$LOG_MESSAGE" | sed -e 's/[\/&]/\\&/g')"
 
-    [[ "$REMOVE_COLORS" == 1 ]] && \
+    [ "$REMOVE_COLORS" ] && \
     ESCAPED_LOG_MESSAGE="$(echo "$ESCAPED_LOG_MESSAGE" | sed 's/\x1b\[[^\x1b]*m//g')"
 
     while IFS= read -r LOG_LINE
     do
-        [[ "$PRINT_LOG" == 1 ]] && \
-        _log_formatter "$LOG_FORMAT" "$LOG_LINE" | tee -a "$LOG_FILE" || \
-        _log_formatter "$LOG_FORMAT" "$LOG_LINE" >> "$LOG_FILE"
+        if [ "$NO_PRINT" ]
+        then
+            prntl_log_formatter "$LOG_FORMAT" "$LOG_LINE" >> "$LOG_FILE"
+        else
+            prntl_log_formatter "$LOG_FORMAT" "$LOG_LINE" | tee -a "$LOG_FILE"
+        fi
     done <<< "$ESCAPED_LOG_MESSAGE"
 }
+
+if [[ ! "$@" ]] && [ -t 0 ]
+then
+    # Print help if no data sent to script.
+    prntl_print_help
+fi
 
 while (( "$#" ))
 do
     case "$1" in
-        -o|--output) LOG_FILE="$2"; shift;;
-        -f|--log-format) LOG_FORMAT="$2"; shift;;
-        -t|--time-format) TIME_FORMAT="$2"; shift;;
-        -c|--no-color) REMOVE_COLORS=1;;
-        -p|--no-print) PRINT_LOG=0;;
-        -h|--help) _show_help;;
-        *) _unknown_option "$1";;
+        -o|--output)
+            if [ "$2" ] && [ ${2:0:1} != '-' ]
+            then
+                LOG_FILE="$2"
+                shift
+            else
+                echo "$0: Missing argument for $1" >&2
+                exit 1
+            fi
+            shift
+            ;;
+        -f|--log-format)
+            if [ "$2" ] && [ ${2:0:1} != '-' ]
+            then
+                LOG_FORMAT="$2"
+                shift
+            else
+                echo "$0: Missing argument for $1" >&2
+                exit 1
+            fi
+            shift
+            ;;
+        -t|--time-format)
+            if [ "$2" ] && [ ${2:0:1} != '-' ]
+            then
+                TIME_FORMAT="$2"
+                shift
+            else
+                echo "$0: Missing argument for $1" >&2
+                exit 1
+            fi
+            shift
+            ;;
+        -c|--no-color)
+            REMOVE_COLORS=1
+            shift
+            ;;
+        -p|--no-print)
+            NO_PRINT=1
+            shift
+            ;;
+        -h|--help)
+            prntl_print_help
+            ;;
+        -*)
+            echo -e "$0: Unknown option: $1\nSee 'prntl --help'." >&2
+            exit 1
+            ;;
+        *)
+            LOG+="$1 "
+            shift
+            ;;
     esac
-    shift
 done
 
-[ ! -t 0 ] && _print_log || _show_help
+prntl_print_log $LOG
diff --git a/rng b/rng
--- a/rng
+++ b/rng
@@ -1,29 +1,105 @@
 #!/bin/bash
 
-#########################################################
+####################################################
 #
-# rng - ranges expander
+#   Based on Kusalananda's answer to question:
+#   https://superuser.com/questions/353496/
 #
-# Based on Kusalananda's answer to question:
-# https://superuser.com/questions/353496/
-#
-#########################################################
+####################################################
 
+# Default delimiters.
+DEL='\n'
+LDEL='\n'
 
-if [[ "$1" && "$(echo "$1" | awk '/[0-9]{1,}\-[0-9]{1,}/')" ]]
-then
-    echo "$1" | awk 'BEGIN { RS=","; FS="-"; ORS="" }
-    NR > 1 { print "\n" }
-    NF > 1 { for (i=$1; i<$2; ++i) { print i "\n" } print $2; next }
-    { print $1 }'
-else
-    cat <<EOF
-rng - ranges expander.
+rng_print_help() {
+cat <<EOF
+Expand ranges like "1-10" into a number series.
 
-This script expands expressions like "1-10" into a number series.
-The resulting row can be used in conjunction with the xargs or
-something else.
+Usage:
+    rng [OPTIONS]... [ARGUMENTS]...
 
-Example: rng 1-4,7,9-12
+Options:
+    -d        digits delimiter. Default: '\n'.
+    -l        lines delimiter. Default: '\n'.
+    -D        Set same delimiters for digits and lines.
+    --help    print this help message and exit.
+
+Example:
+   $ rng 1-4,7,9-12 -D ' '
+   1 2 3 4 7 9 10 11 12
 EOF
-fi
+exit 0
+}
+
+rng_expand() {
+    if [ "$1" ]
+    then
+        STR="$1"
+    else
+        STR="$(cat <&0)"
+    fi
+
+    awk -v del="$DEL" -v ldel="$LDEL" 'BEGIN { RS=","; FS="-"; ORS="" }
+    NR > 1 { print ldel }
+    NF > 1 { for (i=$1; i<$2; ++i) { print i del } print $2; next }
+    { print $1 }' <<< "${STR:0:-1}"  # Cut trailing comma.
+}
+
+[[ ! "$@" ]] && [ -t 0 ] && rng_print_help
+
+while (( "$#" ))
+do
+    case "$1" in
+        -d)
+            if [ "$2" ] && [ "${2:0:1}" != '-' ]
+            then
+                DEL="$2"
+                shift
+            else
+                echo "$0: Missing argument for $1" >&2
+                exit 1
+            fi
+            shift
+            ;;
+        -l)
+            if [ "$2" ] && [ "${2:0:1}" != '-' ]
+            then
+                LDEL="$2"
+                shift
+            else
+                echo "$0: Missing argument for $1" >&2
+                exit 1
+            fi
+            shift
+            ;;
+        -D)
+            if [ "$2" ] && [ "${2:0:1}" != '-' ]
+            then
+                DEL="$2"
+                LDEL="$2"
+                shift
+            else
+                echo "$0: Missing argument for $1" >&2
+                exit 1
+            fi
+            shift
+            ;;
+        --help)
+            rng_print_help
+            ;;
+        *)
+            if [ $(awk '/([0-9]{1,}\-[0-9]{1,})|([0-9]{1,})/' <<< "$1") ] \
+            && [ ! $(awk '/[a-zA-Z*?.+&^%$#@!/\\=><~:\[\]\(\)]/' <<< "$1") ]
+            then
+                ARGS+="$1,"
+            else
+                echo "$0: Bad argument: $1" >&2
+                echo 'The argument can contain only digits and -,' >&2
+                exit 1
+            fi
+            shift
+            ;;
+    esac
+done
+
+rng_expand "$ARGS"
diff --git a/view b/view
--- a/view
+++ b/view
@@ -1,67 +1,59 @@
 #!/usr/bin/env bash
 
-_show_help() {
-    echo -e "view — write highlighted text to STDOUT.\nOptions:
-    \t-l --less \tsend output to less -R
-    \t-n --lines\tless, but shows line nums (less -RN)
-    \t-h --help \tshow this help message and exit."
-    exit 0
+if ! hash highlight 2>/dev/null
+then echo "$0: highlight executable not found." >&2 && exit 1
+fi
+
+view_print_help() {
+cat << EOF
+Print highlighted text to STDOUT.
+
+Usage:
+    view [OPTIONS..] [ARGUMENTS]...
+
+Options:
+    -l --less   send output to 'less -R'
+    -n --lines  less, but shows line nums (less -RN).
+    -h --help   show this help message and exit.
+EOF
+exit 0
 }
 
-_highlight_is_not_installed() {
-    echo -e "'highlight' is not installed" && exit 1
+view_print() {
+    cat "${1:-/dev/stdin}" | highlight -O ansi
 }
 
-_no_such_file() {
-    echo "view: $1: No such file" && exit 1
-}
-
-_view() {
-    ext='sh'
-    case "$1" in
-        *.awk)                 ext='awk';;
-        *.c|*h)                ext='c';;
-        *.conf|*htaccess)      ext='conf';;
-        *.css)                 ext='css';;
-        *.docker|Dockerfile)   ext='docker';;
-        *email)                ext='email';;
-        *.go)                  ext='go';;
-        *.js)                  ext='js';;
-        *.json)                ext='json';;
-        *.md)                  ext='md';;
-        *.ru|*.icu|*.vhost)    ext='nginx';;
-        *.perl|pl)             ext='perl';;
-        *.php)                 ext='php';;
-        *.py)                  ext='python';;
-        Gemfile|Rakefile|*.rb) ext='ruby';;
-        *.sql|*.psql)          ext='sql';;
-        *.tex)                 ext='tex';;
-        *.txt)                 ext='txt';;
-        *.xml)                 ext='xml';;
-        *.yml)                 ext='yml';;
-        *)                     ext='sh';;
-    esac
-    cat "${1:-/dev/stdin}" | highlight -O ansi -S "$ext"
-}
-
-[ $(which highlight) ] || _highlight_is_not_installed
-[[ -t 0 && -z "$1" ]] && _show_help  # Do nothing if no arguments provided and no STDIN
-
-LESS_R=0
-LESS_RN=0
+# Do nothing if no arguments passed and no STDIN.
+[[ -t 0 && -z "$1" ]] && view_print_help
 
 while (( "$#" )); do
     case $1 in
-        -l|--less) LESS_R=1;;
-        -n|-ln|-nl|--lines) LESS_RN=1;;
-        -h|--help) _show_help;;
-        *) if [ -f "$1" ]; then INPUT_FILE="$1"; else _no_such_file "$1"; fi;;
+        -l|--less)
+            LESS_R=1;;
+        -n|-ln|-nl|--lines)
+            LESS_R=1
+            LESS_RN=1;;
+        -h|--help)
+            view_print_help;;
+        *)
+            if [ -f "$1" ]
+            then
+                INPUT_FILE="$1"
+            else
+                echo "$0: No such file: $1" >&2
+                exit 1
+            fi
+            ;;
     esac
     shift
 done
 
-[[ "$LESS_R" == 1 ]] && _view "$INPUT_FILE" | less -R
-[[ "$LESS_RN" == 1 ]] && _view "$INPUT_FILE" | less -RN
-[[ "$LESS_R" == 0 && "$LESS_RN" == 0 ]] && _view "$INPUT_FILE"
-
-unset LESS_R LESS_RN
+if [ "$LESS_R" ] && [ ! "$LESS_RN" ]
+then
+    view_print "$INPUT_FILE" | less -R
+elif [ "$LESS_R" ] && [ "$LESS_RN" ]
+then
+    view_print "$INPUT_FILE" | less -RN
+else
+    view_print "$INPUT_FILE"
+fi
